Assay endpoint with aeid=2065 failed: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).
Traceback (most recent call last):
  File "/home/bossh/pytcpl/src/pipeline/pipeline_main.py", line 43, in pipeline
    df = process(df, config, logger)
  File "/home/bossh/pytcpl/src/pipeline/pipeline_core.py", line 183, in process
    df_to_fit = df[mask].reset_index(drop=True)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 3887, in __getitem__
    return self._getitem_bool_array(key)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/frame.py", line 3943, in _getitem_bool_array
    key = check_bool_indexer(self.index, key)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/indexing.py", line 2575, in check_bool_indexer
    raise IndexingError(
pandas.errors.IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

